suppressPackageStartupMessages(library(SummarizedExperiment))
suppressPackageStartupMessages(library(dplyr))

#' Write SummarizedExperiment to feather files
#'
#' SummarizedExperiment have three parts, colData, rowData and assays. This function will write
#' three parts to feather files, respectively.
#'
#' colData - `feather_dirname`/colData.feather
#' rowData - `feather_dirname`/rowData.feather
#' assays - `feather_dirname`/{assay_name}_assay.feather
#'
#' @param se SummarizedExperiment object
#' @param feather_dirname directory where feather files will save
write_SE2feather <- function(se, feather_dirname) {
  if (!dir.exists(feather_dirname)) {
    dir.create(feather_dirname)
  }

  # Save assays to feather
  assay_names <- names(assays(se))
  for (aname in assay_names) {
    if (is.data.frame(assay(se, aname))) {
      tmp_assay <- assay(se, aname)
    } else {
      tmp_assay <- as.data.frame(assay(se, aname))
    }
    tmp_assay %>%
      tibble::rownames_to_column("gene_id") %>%
      arrow::write_feather(paste0(feather_dirname, "/", aname, "_assay.feather"))
  }

  # Save colData to feather
  colData(se) %>%
    as.data.frame() %>%
    tibble::rownames_to_column("colnames") %>%
    arrow::write_feather(paste0(feather_dirname, "/", "colData.feather"))

  # Save rowData to feather
  rowData(se) %>%
    as.data.frame() %>%
    tibble::rownames_to_column("rownames") %>%
    arrow::write_feather(paste0(feather_dirname, "/", "rowData.feather"))
}


#' Read SummariedExperiment object from feather files generated by `write_SE2feather`
#'
#' Read SummariedExperiment three parts from feather files
#'
#' colData - `feather_dirname`/colData.feather
#' rowData - `feather_dirname`/rowData.feather
#' assays - `feather_dirname`/{assay_name}_assay.feather
#'
#' @param feather_dirname directory where feather files will save
read_SE4feather <- function(feather_dirname) {
  # Read assays
  assay_files <- list.files(feather_dirname, ".+_assay\\.feather$", full.names = TRUE)
  assay_names <- stringr::str_extract(assay_files, "(?<=/)([^/]+)(?=_assay\\.feather)")
  assay_list <- list()
  for (i in seq_along(assay_files)) {
    assay_list[[assay_names[i]]] <- arrow::read_feather(assay_files[i]) %>%
      tibble::column_to_rownames("gene_id")
  }

  # Read colData
  coldata <- arrow::read_feather(paste0(feather_dirname, "/", "colData.feather")) %>%
    tibble::column_to_rownames("colnames")

  # Read rowData
  rowdata <- arrow::read_feather(paste0(feather_dirname, "/", "rowData.feather")) %>%
    tibble::column_to_rownames("rownames")

  SummarizedExperiment::SummarizedExperiment(assay_list, rowData = rowdata, colData = coldata)
}
